version: '3.9'

services:
  redis:
    container_name: redis_test_a
    image: redis:7.2.4
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  mongo:
    container_name: mongo_test_a
    image: mongo:7.0.6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      
volumes:
  redis-data:
  mongo-data:
