version: '3.9'

services:
  fog_energy:
    image: henriqueabv/fog_water:latest
    container_name: fog_energy
    ports:
      - "8765:8765"
      - "8766:8766"
      - "8000:8000"
      - "5683:5683/udp"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_DB}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
    extra_hosts:
      - "sftp_server:192.168.56.101"
    depends_on:
      - redis
      - mongo
    networks:
      - fog_network

  redis:
    container_name: redis
    image: redis:7.2.4
    ports:
      - "6380:6379"
    networks:
      - fog_network

  mongo:
    container_name: mongo
    image: mongo:7.0.6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    networks:
      - fog_network

networks:
  fog_network:
    driver: bridge
