version: '3.9'

services:

  processing:
    container_name: processing
    restart: unless-stopped
    build:
      context: ./processing
    depends_on:
      - mongo
      - redis
    networks:
      - minha_rede

  protocols:
    container_name: protocols
    restart: unless-stopped
    build:
      context: ./protocols
    depends_on:
      - mongo
      - redis
      - processing
    networks:
      - minha_rede
    extra_hosts:
      - "sftp_server:192.168.56.101"

  orchestration:
    container_name: orchestration
    restart: unless-stopped
    build:
      context: ./orchestration
    depends_on:
      - processing
    networks:
      - minha_rede

  redis:
    container_name: redis_test_b
    image: redis:7.2.4
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - minha_rede

  mongo:
    container_name: mongo_test_b
    image: mongo:7.0.6
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    networks:
      - minha_rede
      
volumes:
  redis-data:
  mongo-data:

networks:
  minha_rede:
    driver: bridge
